

const CHANGE_USER_STATE = 'CHANGE_USER_STATE'
const CHANGE_USER_INFO = 'CHANGE_USER_INFO'
const CHANGE_CATEGORY_LIST = 'CHANGE_CATEGORY_LIST'
const CHANGE_DETAIL_COMMON_INFO = 'CHANGE_DETAIL_COMMON_INFO'

export  { CHANGE_USER_STATE, CHANGE_USER_INFO, CHANGE_CATEGORY_LIST, CHANGE_DETAIL_COMMON_INFO }